env:
  browser: true
  es2021: true
extends:
  - airbnb-base
  - prettier
parser: '@typescript-eslint/parser'
parserOptions:
  project: ./tsconfig.json
plugins:
  - '@typescript-eslint'
rules:
  import/no-extraneous-dependencies: off
  '@typescript-eslint/strict-boolean-expressions': error
