on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Setup vars
        id: vars
        run: echo "::set-output name=version::${GITHUB_REF##*/v}"

      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: npm
          registry-url: https://registry.npmjs.org

      - run: npm i -g npm@8

      - run: npm ci

      - run: npm run check

      - run: npm run build

      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
